Machine Learning Exercises 2 - Osiel Vivar - ov35

In [239]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

(1) Logistic Regression

In [240]:
#(a)
n = 4
m = 1000

X = np.random.normal(0,1,(m,n))
print(X)

[[-0.97989532  0.02450541 -1.97480605 -0.47664278]
 [-0.97584598 -0.14339035 -1.53179847 -1.04901409]
 [ 0.15050858 -2.02958385 -0.02682887 -0.66197864]
 ...
 [ 0.42466262  0.30472371 -0.35666108  1.63343242]
 [ 1.16419883  0.04308879 -1.58648828 -0.07187771]
 [ 0.38143825 -1.01357102  0.11145263 -0.68791473]]


In [241]:
#(b)
theta_b = np.array([[1,-1,2,-5]]).T
print(theta_b)
#assuming i is the row indicator of X, y will also be a column vector of size m. Where values will either be 0 or 1 depending on sign(z)
# z = theta * x(i) + 0.5
y_nosign = np.matmul(X,theta_b) + 0.5 #this is questionable
#print(y)

print("\n sign function: \n")
y= np.sign(y_nosign) #this is what we want to generate, the correct labels
print(y) #we will compare this to our generated model using LR
print(np.size(y))
print(y.shape)

[[ 1]
 [-1]
 [ 2]
 [-5]]

 sign function: 

[[-1.]
 [ 1.]
 [ 1.]
 [-1.]
 [ 1.]
 [-1.]
 [-1.]
 [-1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [-1.]
 [ 1.]
 [ 1.]
 [-1.]
 [ 1.]
 [ 1.]
 [-1.]
 [ 1.]
 [ 1.]
 [-1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [-1.]
 [-1.]
 [ 1.]
 [ 1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [ 1.]
 [-1.]
 [-1.]
 [ 1.]
 [-1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [ 1.]
 [ 1.]
 [-1.]
 [ 1.]
 [-1.]
 [ 1.]
 [-1.]
 [-1.]
 [ 1.]
 [ 1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [ 1.]
 [ 1.]
 [-1.]
 [ 1.]
 [-1.]
 [ 1.]
 [-1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [-1.]
 [-1.]
 [-1.]
 [-1.]
 [ 1.]
 [-1.]
 [ 1.]
 [-1.]
 [-1.]
 [-1.]
 [ 1.]
 [-1.]
 [-1.]
 [-1.]
 [ 1.]
 [ 1.]
 [-1.]
 [ 1.]
 [ 1.]
 [-1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [-1.]
 [ 1.]
 [-1.]
 [ 1.]
 [-1.]
 [ 1.]
 [ 1.]
 [-1.]
 [-1.]
 [ 1.]
 [-1.]
 [-1.]
 [ 1.]
 [-1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [-1.]
 [ 1.]
 [ 1.]
 [-1.]
 [-1.]
 [ 1.]
 [-1.]
 [-1.]
 [-1.]
 [ 1.]
 [-1.]
 [ 1.]
 [ 1.]
 [-1.]
 [ 1.]
 [-1

In [242]:
#Creating Necessary functions for Logisitic Regression

#define sigmoid function
def sigmoid(zeta):
    output = 1 / (1 + np.exp(-zeta))
    return output

#Gradient Descent Functions
def update(X, y, alpha, iteration, w_b):
    m = X.shape[0]
    theta = np.reshape(w_b["theta"],(4,1)) #feautre of w_b --> weights
    bias = w_b["bias"] #feature of w_b --> bias
    for i in range(iteration): 
        sigma_out = sigmoid(np.dot(X, theta) + bias) # sigmoid(theta*x+bias)
        cost = -1/m * np.sum(y * np.log(sigma_out)) + (1 - y) * np.log(1-sigma_out) # 1/m scalar to account for each individual sample

        #GD for Logistic Regression
        dtheta = 1/m * np.dot(X.T, (sigma_out - y))
        theta -= alpha * dtheta #Updating the weights incrementally

        # Accounting for Bias
        db = 1/m * np.sum(sigma_out - y) #raw error to make bias
        bias -= alpha * db #updating biases incrementally

        w_b["theta"] = theta
        w_b["bias"] = bias
        
      #should be printing the final weights
    return w_b #value we want to assign when using this function is weights and biases



In [243]:
#(c)
#Executing Gradient Descent/Initialization
alpha = 0.1 / m #step size
iterations = 1000 

init_parameters = {} 
init_parameters["theta"] = np.zeros(X.shape[1])
init_parameters["bias"] = 0

# Define the train function
def train(X,y,alpha,iterations):
    parameters_out = update(X, y, alpha, iterations, init_parameters)
    return parameters_out

 #assigning the new w_b (weights and biases)
# Train the model
parameters_out = train(X, y, alpha, iterations)
print("Weights/Theta: \n", parameters_out['theta'],"\nbias: ", parameters_out['bias'])

# Predict using the trained model
output_values = np.dot(X[:1000], parameters_out["theta"]) + parameters_out["bias"]
predictions = sigmoid(output_values) >= 1/2

for i in range(m):
    if predictions[i]:
        predictions == 1
    else:
        predictions == -1
print(predictions)


Weights/Theta: 
 [[ 0.00856752]
 [-0.01620889]
 [ 0.03260562]
 [-0.07191786]] 
bias:  -0.04380335389507819
[[False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [

In [244]:
#(d)
#make Z, gaussian of mean 0, var = 2
Z = np.random.normal(0,2,(m,1))
#add it to the original y 
y_nosign_noisy = y_nosign + Z #add noise to the 

#sign the y_noisy
y_noisy = np.sign(y_nosign_noisy) #y_sign_noisy --> 

parameters_out_noisy = train(X, y_noisy, alpha, iterations)
print("Weights/Theta: \n", parameters_out_noisy['theta'],"\nbias: ", parameters_out_noisy['bias'])

noisy_output= np.dot(X[:1000], parameters_out_noisy["theta"]) + parameters_out_noisy["bias"]
noisy_predictions = sigmoid(noisy_output) >= 1/2
print(noisy_predictions)


Weights/Theta: 
 [[ 0.01947088]
 [-0.02980691]
 [ 0.05990409]
 [-0.1393057 ]] 
bias:  -0.08822193140683904
[[False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [

In [ ]:
#(e)


Problem #2 Logistic Regression Using Python

In [245]:
from sklearn.linear_model import LogisticRegression

y_reshaped = y.flatten()
y_noisy_reshaped = y_noisy.flatten()

#fitting
lr_model = LogisticRegression().fit(X,y_reshaped)
lr_noisy_model = LogisticRegression().fit(X,y_noisy_reshaped)
#prediciting
lr_pred = lr_model.predict(X)
lr_noisy_pred = lr_noisy_model.predict(X)
#score
lr_score = lr_model.score(X,y)
lr_noisy_score = lr_noisy_model.score(X,y)

print(lr_score)
print(lr_noisy_score)



0.995
0.985


3) Non-Centered Data and Principal Component Analysis

In [246]:
#(a)
A = np.random.normal(0,1,(3,2))
print(A)

c = np.random.normal(0,3,size =3)
print(c)

[[-0.16880735  1.76099607]
 [ 0.04948007  1.08772817]
 [-1.22981289 -0.27014916]]
[ 6.19744668 -1.52394456  3.54186211]


In [247]:
#(b)

# {x ^ i} ^250 , where each individual x^i 
# x(i) = A*b_i + c , b_i is R^2 --> b_i is two elements
X_3 = np.zeros((250,3))
for i in range(250):
    b = np.random.normal(0,1,(2,)) #because of the for loop a new b is being generated everytime
    X_3[i] = A.dot(b) + c

print("Input data X for problem 3 : \n", X_3)
X_3 = X_3.T

Input data X for problem 3 : 
 [[ 4.82347929 -2.26079391  2.83937403]
 [ 4.65406734 -2.54763875  4.35346595]
 [ 8.84253041 -0.10790498  4.91467702]
 [ 4.57299493 -2.68135855  5.04904082]
 [ 4.98780961 -2.14939646  2.7333553 ]
 [ 7.06890207 -1.01951737  3.68464927]
 [ 7.55216087 -0.74210006  3.78268793]
 [ 6.6547909  -1.20607224  3.18273599]
 [ 2.09253429 -4.02239076  3.8688475 ]
 [ 6.98401826 -1.16398434  4.44935658]
 [ 7.11281806 -1.23733266  5.67841756]
 [ 5.55880922 -1.8667115   3.21754215]
 [ 5.73685037 -1.7844861   3.41684429]
 [ 8.13990115 -0.50337065  4.70775674]
 [ 5.92495961 -1.35153287  0.80089815]
 [ 4.54173996 -2.46540002  3.13236665]
 [ 6.6040166  -1.14560631  2.44053872]
 [ 5.31193261 -1.77417023  1.25417237]
 [ 6.24461926 -1.50481209  3.61633913]
 [ 7.33411235 -0.88541098  3.88659887]
 [ 8.45220819 -0.29007721  4.49332935]
 [ 6.662114   -1.16568683  2.8887165 ]
 [ 5.9186631  -1.53204301  2.24437783]
 [ 5.70623945 -2.01552699  5.15409308]
 [ 3.95991663 -3.0277417   4.8792

In [248]:
#(c)
print("Rank of X_3 = ", np.linalg.matrix_rank(X_3))


Rank of X_3 =  3


In [249]:
#(d)

#the principal directions : u1 and u2 will be the 2 largest eigenvectors
#from class we must use the covariance
covar = np.cov(X_3)

e_val , e_vect = np.linalg.eig(covar)
#in this case mean is NOT 0

eig_vector = e_vect[:, 1:] #necessary for using only desired evect

principal_directions = np.zeros((3,2))
principal_directions[:,0] = e_vect[:,0]
principal_directions[:,1] = e_vect[:,1]

print(principal_directions)


[[-0.84961094 -0.51098698]
 [-0.51977531  0.85321675]
 [ 0.08941411  0.10446758]]
